theme: Portfolio Perfect 

title: My GitHub Pages Site
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my GitHub Pages site using the Minimal theme.
theme: Portfolio Perfect 

# Optional settings
markdown: kramdown
paginate: 5
